apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tg-calendar-bot.fullname" . }}-config
  namespace: {{ include "tg-calendar-bot.namespace" . }}
  labels:
    {{- include "tg-calendar-bot.labels" . | nindent 4 }}
data:
  gigachat-model: {{ .Values.configMap.gigachatModel | quote }}

