{{- if and .Values.redis.enabled .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.redis.name }}-pvc
  namespace: {{ include "tg-calendar-bot.namespace" . }}
  labels:
    {{- include "tg-calendar-bot.redis.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.redis.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
  {{- if .Values.redis.persistence.storageClass }}
  {{- if (eq "-" .Values.redis.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.redis.persistence.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}

