apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tg-calendar-bot.fullname" . }}-secrets
  namespace: {{ include "tg-calendar-bot.namespace" . }}
  labels:
    {{- include "tg-calendar-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  telegram-bot-token: {{ .Values.secrets.telegramBotToken | quote }}
  gigachat-auth-key: {{ .Values.secrets.gigachatAuthKey | quote }}
  google-credentials: {{ .Values.secrets.googleCredentials | quote }}

