{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tg-calendar-bot.serviceAccountName" . }}
  namespace: {{ include "tg-calendar-bot.namespace" . }}
  labels:
    {{- include "tg-calendar-bot.labels" . | nindent 4 }}
{{- end }}

